const Fields = {
  isActive: "isActive",
  isApproved: "isApproved",
  isVerified: "isVerified",
  isAccepted: "isAccepted",
  isAnswered: "isAnswered",
  offerLetters: "offerLetters",
  profileImages: "profileImages",
  currentEmployerId: "currentEmployerId",
  verificationByEmail: "verificationByEmail",
  companyLocation: "companyLocation",
  employeeEmail: "employeeEmail",
  employerEmail: "employerEmail",
  employerId: "employerId",
  employeeId: "employeeId",
  companyId: "companyId",
  resumes: "resumes",
  isLive: "isLive",
};
export { Fields };
